#!/bin/bash

set -e

VOLUME_PATH="$(dirname "$0")"

if [[ -d "/Applications/AppleHole.app" ]]; then
  cp "${VOLUME_PATH}/com.user.applehole.daemon.plist" "$HOME/Library/LaunchAgents/com.user.applehole.daemon.plist"
  launchctl bootstrap user/$(id -u) com.user.applehole.daemon
  launchctl start com.user.applehole.daemon.plist
else
  echo "Please drop AppleHole into your applications before installing the Daemon"
fi
